allow-branch = ["main", "dev", "!HEAD"]
publish = false
pre-release-commit-message = "chore: Release {{crate_name}} version {{version}}"
pre-release-replacements = []
tag-message = "chore: Release {{crate_name}} version {{version}}"
tag-name = "v{{version}}"
