[package]
name = "native_{{crate_name}}"
version = "0.1.0"
edition = "2021"
workspace = "../.."

[features]
default = []
inspect = ["{{crate_name}}/inspect"]

[dependencies]
bevy.workspace = true
{{crate_name}} = { path = "../.." }
