[tasks.run-web]
env_files = ["../../.env"]
command = "mold"
args = [
    "-run",
    "trunk",
    "serve",
    "--open",
    "--no-default-features",
    "--features",
    "inspect",
]

[tasks.release-web]
env_files = ["../../.env"]
command = "mold"
args = ["-run", "trunk", "build", "--release"]
