# Learn more: https://trunkrs.dev/configuration/#trunk-toml
[build]
target = "index.html"

[watch]
watch = [
    "../../src",    # Game source
    "src",          # WASM launcher source
    "index.html",
    "main.scss",
]
