name: Build Android

permissions:
  contents: write

env:
  APP_NAME: {{crate_name}}

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - ".github/build.yml"
      - ".github/build-**.yml"
      - ".github/release-**.yml"
      - "**/Makefile.toml"
      - "README.md"
    tags:
      - "v*"
{% raw %}
jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  native_build:
    container: sergioribera/rust-android:170-sdk-33
    needs: ci
    outputs:
      APP_NAME: ${{env.APP_NAME}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Load .env file
        uses: xom9ikk/dotenv@v2
      - run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > ${{ env.APP_NAME }}.keystore
      # Start to build
      - name: build apk
        run: gradle assembleRelease -p launchers/mobile/android
      - name: build aab
        run: gradle bundleRelease -p launchers/mobile/android
      - name: Rename APK
        run: |
          cp launchers/mobile/android/build/outputs/apk/release/android-release-unsigned.apk ${{ env.APP_NAME }}.apk
          cp launchers/mobile/android/build/outputs/bundle/release/android-release.aab ${{ env.APP_NAME }}.aab
      - name: Sign Bundles
        run: |
          echo "${{ secrets.KEYSTORE_PASSWORD }}" | apksigner sign --ks ${{ env.APP_NAME }}.keystore --ks-key-alias ${{ env.APP_NAME }} ${{ env.APP_NAME }}.apk
          echo "${{ secrets.KEYSTORE_PASSWORD }}" | jarsigner -keystore ${{ env.APP_NAME }}.keystore ${{ env.APP_NAME }}.aab ${{ env.APP_NAME }}
      - name: Post Build | Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APP_NAME }}.apk
          path: ${{ env.APP_NAME }}.apk
{% endraw %}
{% if deploy_play_store %}
      - name: Upload to Playstore
        uses: r0adkll/upload-google-play@v1
        with:
          inAppUpdatePriority: 2
          packageName: {{pkg_name}}
          track: production
{% raw %}
          releaseFiles: ${{ env.APP_NAME }}.aab
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
{% endraw %}
{% endif %}
{% if deploy_release %}
{% raw %}
      - name: Release | Upload
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.APP_NAME }}.apk
          prerelease: ${{ contains(github.ref_name, 'a') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
{% endraw %}
{% endif %}

{% if deploy_itch %}
  upload-itch:
    needs: build_native
    secrets: inherit
    uses: ./.github/workflows/itch.yml
    with:
      author: {{itch_username}}
      name: {{ itch_project_name }}
{% raw %}
      file_name: ${{ needs.native_build.outputs.APP_NAME }}.apk
      os: android
{% endraw %}
{% endif %}
