jobs:
  # Run cargo clippy -- -D warnings
  clippy_check:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: dsherret/rust-toolchain-file@v1
      - name: Load .env file
        uses: xom9ikk/dotenv@v2
      - name: Install dependencies
        run: |
          echo "${{ github.ref_name }}"
          export DEBIAN_FRONTED=noninteractive
          sudo apt-get -qq update
          sudo apt-get install -y libxdo-dev libasound2-dev libudev-dev pkg-config
      - name: Run clippy
        uses: actions-rs/cargo@v1.0.1
        with:
          args: -- -D warnings
          command: clippy

  # Run cargo fmt --all -- --check
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - uses: dsherret/rust-toolchain-file@v1
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1.0.1
        with:
          args: --all -- --check
          command: fmt

name: CI
on:
  pull_request:
    branches:
      - main
      - dev
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "**/Makefile.toml"
      - "README.md"
    tags-ignore:
      - "v**"
  workflow_call:
